################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/Blip_Buffer.cpp \
../src/Sync_Audio.cpp \
../src/about.cpp \
../src/bitkeypad.cpp \
../src/breakpoints.cpp \
../src/cd4536b.cpp \
../src/cdp1802.cpp \
../src/cdp1852.cpp \
../src/cdp18s020.cpp \
../src/cdp18s600.cpp \
../src/cdp18s640.cpp \
../src/cidelsa.cpp \
../src/cidelsastatusbar.cpp \
../src/coinarcade.cpp \
../src/colour.cpp \
../src/computer.cpp \
../src/comx35.cpp \
../src/comxstatusbar.cpp \
../src/configuration.cpp \
../src/cosmicos.cpp \
../src/cosmicoshex.cpp \
../src/cvkeypad.cpp \
../src/datadir.cpp \
../src/debug.cpp \
../src/diagstatusbar.cpp \
../src/elf.cpp \
../src/elf2.cpp \
../src/elf2k.cpp \
../src/elf2kdisk.cpp \
../src/elf2khex.cpp \
../src/elf2kswitch.cpp \
../src/encrypt.cpp \
../src/eti660.cpp \
../src/expansion.cpp \
../src/fdc.cpp \
../src/fred.cpp \
../src/functionkey.cpp \
../src/guicdp18s020.cpp \
../src/guicdp18s600.cpp \
../src/guicidelsa.cpp \
../src/guicomx.cpp \
../src/guicosmicos.cpp \
../src/guidiag.cpp \
../src/guielf.cpp \
../src/guielf2k.cpp \
../src/guieprom.cpp \
../src/guieti660.cpp \
../src/guifred.cpp \
../src/guimain.cpp \
../src/guimcds.cpp \
../src/guimembership.cpp \
../src/guimicrotutor.cpp \
../src/guims2000.cpp \
../src/guinano.cpp \
../src/guipecom.cpp \
../src/guipico.cpp \
../src/guipopup.cpp \
../src/guisb.cpp \
../src/guistudio2.cpp \
../src/guitmc2000.cpp \
../src/guitmc600.cpp \
../src/guiuc1800.cpp \
../src/guivelf.cpp \
../src/guivip.cpp \
../src/guivip2.cpp \
../src/guivip2k.cpp \
../src/guixml.cpp \
../src/hbelf.cpp \
../src/i8275.cpp \
../src/ide.cpp \
../src/iodevice.cpp \
../src/joycard.cpp \
../src/keyb1871.cpp \
../src/keyblatch.cpp \
../src/keybmatrix.cpp \
../src/keyboard.cpp \
../src/keymap.cpp \
../src/keymaptmc.cpp \
../src/keypad.cpp \
../src/keypadfred.cpp \
../src/led.cpp \
../src/ledmodule.cpp \
../src/mac.cpp \
../src/main.cpp \
../src/mc6845.cpp \
../src/mc6847.cpp \
../src/mcds.cpp \
../src/member.cpp \
../src/memory.cpp \
../src/microsetup.cpp \
../src/microtutor.cpp \
../src/microtutor2.cpp \
../src/ms2000.cpp \
../src/nano.cpp \
../src/network.cpp \
../src/pecom.cpp \
../src/pico.cpp \
../src/pio.cpp \
../src/pixie.cpp \
../src/portext.cpp \
../src/ports.cpp \
../src/printer.cpp \
../src/ps2.cpp \
../src/ps2gpio.cpp \
../src/psave.cpp \
../src/pushbutton.cpp \
../src/rtc.cpp \
../src/serial.cpp \
../src/sn76430n.cpp \
../src/sound.cpp \
../src/splash.cpp \
../src/studio2.cpp \
../src/studioiv.cpp \
../src/super.cpp \
../src/til.cpp \
../src/til313.full.cpp \
../src/tmc1800.cpp \
../src/tmc2000.cpp \
../src/tmc600.cpp \
../src/tms9918.cpp \
../src/uc1800.cpp \
../src/upd765.cpp \
../src/usb.cpp \
../src/v1870.cpp \
../src/velf.cpp \
../src/victory.cpp \
../src/video.cpp \
../src/vip.cpp \
../src/vip2.cpp \
../src/vip2k.cpp \
../src/vip2statusbar.cpp \
../src/vis1870.cpp \
../src/visicom.cpp \
../src/vt100.cpp \
../src/vtsetup.cpp \
../src/waveReader.cpp \
../src/waveWriter.cpp \
../src/wxcurl_base.cpp \
../src/wxcurl_dialog.cpp \
../src/wxcurl_ftp.cpp \
../src/wxcurl_http.cpp \
../src/wxcurl_panel.cpp \
../src/wxcurl_thread.cpp \
../src/xmlemu.cpp \
../src/xmlparser.cpp

C_SRCS += \
../src/SDL_audioin.c \
../src/audioin_devdsp.c \
../src/audioin_windib.c 

OBJS += \
./src/Blip_Buffer.o \
./src/SDL_audioin.o \
./src/Sync_Audio.o \
./src/about.o \
./src/audioin_devdsp.o \
./src/audioin_windib.o \
./src/bitkeypad.o \
./src/breakpoints.o \
./src/cd4536b.o \
./src/cdp1802.o \
./src/cdp1852.o \
./src/cdp18s020.o \
./src/cdp18s600.o \
./src/cdp18s640.o \
./src/cidelsa.o \
./src/cidelsastatusbar.o \
./src/coinarcade.o \
./src/colour.o \
./src/computer.o \
./src/comx35.o \
./src/comxstatusbar.o \
./src/configuration.o \
./src/cosmicos.o \
./src/cosmicoshex.o \
./src/cvkeypad.o \
./src/datadir.o \
./src/debug.o \
./src/diagstatusbar.o \
./src/elf.o \
./src/elf2.o \
./src/elf2k.o \
./src/elf2kdisk.o \
./src/elf2khex.o \
./src/elf2kswitch.o \
./src/encrypt.o \
./src/eti660.o \
./src/expansion.o \
./src/fdc.o \
./src/fred.o \
./src/functionkey.o \
./src/guicdp18s020.o \
./src/guicdp18s600.o \
./src/guicidelsa.o \
./src/guicomx.o \
./src/guicosmicos.o \
./src/guidiag.o \
./src/guielf.o \
./src/guielf2k.o \
./src/guieprom.o \
./src/guieti660.o \
./src/guifred.o \
./src/guimain.o \
./src/guimcds.o \
./src/guimembership.o \
./src/guimicrotutor.o \
./src/guims2000.o \
./src/guinano.o \
./src/guipecom.o \
./src/guipico.o \
./src/guipopup.o \
./src/guisb.o \
./src/guistudio2.o \
./src/guitmc2000.o \
./src/guitmc600.o \
./src/guiuc1800.o \
./src/guivelf.o \
./src/guivip.o \
./src/guivip2.o \
./src/guivip2k.o \
./src/guixml.o \
./src/hbelf.o \
./src/i8275.o \
./src/ide.o \
./src/iodevice.o \
./src/joycard.o \
./src/keyb1871.o \
./src/keyblatch.o \
./src/keybmatrix.o \
./src/keyboard.o \
./src/keymap.o \
./src/keymaptmc.o \
./src/keypad.o \
./src/keypadfred.o \
./src/led.o \
./src/ledmodule.o \
./src/mac.o \
./src/main.o \
./src/mc6845.o \
./src/mc6847.o \
./src/mcds.o \
./src/member.o \
./src/memory.o \
./src/microsetup.o \
./src/microtutor.o \
./src/microtutor2.o \
./src/ms2000.o \
./src/nano.o \
./src/network.o \
./src/pecom.o \
./src/pico.o \
./src/pio.o \
./src/pixie.o \
./src/portext.o \
./src/ports.o \
./src/printer.o \
./src/ps2.o \
./src/ps2gpio.o \
./src/psave.o \
./src/pushbutton.o \
./src/rtc.o \
./src/serial.o \
./src/sn76430n.o \
./src/sound.o \
./src/splash.o \
./src/studio2.o \
./src/studioiv.o \
./src/super.o \
./src/til.o \
./src/til313.full.o \
./src/tmc1800.o \
./src/tmc2000.o \
./src/tmc600.o \
./src/tms9918.o \
./src/uc1800.o \
./src/upd765.o \
./src/usb.o \
./src/v1870.o \
./src/velf.o \
./src/victory.o \
./src/video.o \
./src/vip.o \
./src/vip2.o \
./src/vip2k.o \
./src/vip2statusbar.o \
./src/vis1870.o \
./src/visicom.o \
./src/vt100.o \
./src/vtsetup.o \
./src/waveReader.o \
./src/waveWriter.o \
./src/wxcurl_base.o \
./src/wxcurl_dialog.o \
./src/wxcurl_ftp.o \
./src/wxcurl_http.o \
./src/wxcurl_panel.o \
./src/wxcurl_thread.o \
./src/xmlemu.o \
./src/xmlparser.o


CPP_DEPS += \
./src/Blip_Buffer.d \
./src/Sync_Audio.d \
./src/about.d \
./src/bitkeypad.d \
./src/breakpoints.d \
./src/cd4536b.d \
./src/cdp1802.d \
./src/cdp1852.d \
./src/cdp18s020.d \
./src/cdp18s600.d \
./src/cdp18s640.d \
./src/cidelsa.d \
./src/cidelsastatusbar.d \
./src/coinarcade.d \
./src/colour.d \
./src/computer.d \
./src/comx35.d \
./src/comxstatusbar.d \
./src/configuration.d \
./src/cosmicos.d \
./src/cosmicoshex.d \
./src/cvkeypad.d \
./src/datadir.d \
./src/debug.d \
./src/diagstatusbar.d \
./src/elf.d \
./src/elf2.d \
./src/elf2k.d \
./src/elf2kdisk.d \
./src/elf2khex.d \
./src/elf2kswitch.d \
./src/encrypt.d \
./src/eti660.d \
./src/expansion.d \
./src/fdc.d \
./src/fred.d \
./src/functionkey.d \
./src/guicdp18s020.d \
./src/guicdp18s600.d \
./src/guicidelsa.d \
./src/guicomx.d \
./src/guicosmicos.d \
./src/guidiag.d \
./src/guielf.d \
./src/guielf2k.d \
./src/guieprom.d \
./src/guieti660.d \
./src/guifred.d \
./src/guimain.d \
./src/guimcds.d \
./src/guimembership.d \
./src/guimicrotutor.d \
./src/guims2000.d \
./src/guinano.d \
./src/guipecom.d \
./src/guipico.d \
./src/guipopup.d \
./src/guisb.d \
./src/guistudio2.d \
./src/guitmc2000.d \
./src/guitmc600.d \
./src/guiuc1800.d \
./src/guivelf.d \
./src/guivip.d \
./src/guivip2.d \
./src/guivip2k.d \
./src/guixml.d \
./src/hbelf.d \
./src/i8275.d \
./src/ide.d \
./src/iodevice.d \
./src/joycard.d \
./src/keyb1871.d \
./src/keyblatch.d \
./src/keybmatrix.d \
./src/keyboard.d \
./src/keymap.d \
./src/keymaptmc.d \
./src/keypad.d \
./src/keypadfred.d \
./src/led.d \
./src/ledmodule.d \
./src/mac.d \
./src/main.d \
./src/mc6845.d \
./src/mc6847.d \
./src/mcds.d \
./src/member.d \
./src/memory.d \
./src/microsetup.d \
./src/microtutor.d \
./src/microtutor2.d \
./src/ms2000.d \
./src/nano.d \
./src/network.d \
./src/pecom.d \
./src/pico.d \
./src/pio.d \
./src/pixie.d \
./src/portext.d \
./src/ports.d \
./src/printer.d \
./src/ps2.d \
./src/ps2gpio.d \
./src/psave.d \
./src/pushbutton.d \
./src/rtc.d \
./src/serial.d \
./src/sn76430n.d \
./src/sound.d \
./src/splash.d \
./src/studio2.d \
./src/studioiv.d \
./src/super.d \
./src/til.d \
./src/til313.full.d \
./src/tmc1800.d \
./src/tmc2000.d \
./src/tmc600.d \
./src/tms9918.d \
./src/uc1800.d \
./src/upd765.d \
./src/usb.d \
./src/v1870.d \
./src/velf.d \
./src/victory.d \
./src/video.d \
./src/vip.d \
./src/vip2.d \
./src/vip2k.d \
./src/vip2statusbar.d \
./src/vis1870.d \
./src/visicom.d \
./src/vt100.d \
./src/vtsetup.d \
./src/waveReader.d \
./src/waveWriter.d \
./src/wxcurl_base.d \
./src/wxcurl_dialog.d \
./src/wxcurl_ftp.d \
./src/wxcurl_http.d \
./src/wxcurl_panel.d \
./src/wxcurl_thread.d \
./src/xmlemu.d \
./src/xmlparser.d

C_DEPS += \
./src/SDL_audioin.d \
./src/audioin_devdsp.d \
./src/audioin_windib.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -D__WXGTK__ -I/usr/include/SDL -I../images -O3 -Wall -c -fmessage-length=0 `wx-config --cxxflags --debug=no` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I/usr/include/SDL -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


