#!/bin/sh 
#!/bin/sh
if test -d /usr/share/emma_02/data/FRED1_5/FRED2
then
   rm -r /usr/share/emma_02/data/FRED2
   rm -r /usr/share/emma_02/data/FRED1_5/FRED2
fi
if test -d /usr/share/emma_02/Configurations/FRED1_5/FRED2
then
  rm -r /usr/share/emma_02/Configurations/FRED2
  rm -r /usr/share/emma_02/Configurations/FRED1_5/FRED2
fi
if test -d /usr/share/emma_02/data/CDP18S600
then
  rm /usr/share/emma_02/data/CDP18S600/*.*
  rmdir /usr/share/emma_02/data/CDP18S600
fi
if test -d /usr/share/emma_02/data/CDP18S601
then
  rm /usr/share/emma_02/data/CDP18S601/*.*
  rmdir /usr/share/emma_02/data/CDP18S601
fi
if test -d /usr/share/emma_02/data/CDP18S603A
then
  rm /usr/share/emma_02/data/CDP18S603A/*.*
  rmdir /usr/share/emma_02/data/CDP18S603A
fi
if test -d /usr/share/emma_02/Configurations/CDP18S600
then
  rm /usr/share/emma_02/Configurations/CDP18S600/*.*
  rmdir /usr/share/emma_02/Configurations/CDP18S600
fi
if test -d /usr/share/emma_02/Configurations/CDP18S601
then
  rm /usr/share/emma_02/Configurations/CDP18S601/*.*
  rmdir /usr/share/emma_02/Configurations/CDP18S601
fi
if test -d /usr/share/emma_02/Configurations/CDP18S603A
then
  rm /usr/share/emma_02/Configurations/CDP18S603A/*.*
  rmdir /usr/share/emma_02/Configurations/CDP18S603A
fi
