#!/bin/sh 
if test -d /usr/share/emma_02/data/FRED2
then
   mv /usr/share/emma_02/data/FRED2 /usr/share/emma_02/data/FRED1_5
fi
if test -d /usr/share/emma_02/Configurations/FRED2
then
  mv /usr/share/emma_02/Configurations/FRED2 /usr/share/emma_02/Configurations/FRED1_5
fi
if test -d /usr/share/emma_02/data/CDP18S600
then
  rm /usr/share/emma_02/data/CDP18S600/*.*
  rmdir /usr/share/emma_02/data/CDP18S600
fi
if test -d /usr/share/emma_02/data/CDP18S601
then
  rm /usr/share/emma_02/data/CDP18S601/*.*
  rmdir /usr/share/emma_02/data/CDP18S601
fi
if test -d /usr/share/emma_02/data/CDP18S603A
then
  rm /usr/share/emma_02/data/CDP18S603A/*.*
  rmdir /usr/share/emma_02/data/CDP18S603A
fi
if test -d /usr/share/emma_02/Configurations/CDP18S600
then
  rm /usr/share/emma_02/Configurations/CDP18S600/*.*
  rmdir /usr/share/emma_02/Configurations/CDP18S600
fi
if test -d /usr/share/emma_02/Configurations/CDP18S601
then
  rm /usr/share/emma_02/Configurations/CDP18S601/*.*
  rmdir /usr/share/emma_02/Configurations/CDP18S601
fi
if test -d /usr/share/emma_02/Configurations/CDP18S603A
then
  rm /usr/share/emma_02/Configurations/CDP18S603A/*.*
  rmdir /usr/share/emma_02/Configurations/CDP18S603A
fi
