#ifndef DEFINITION_H
#define DEFINITION_H

#define MAXROM 6
#define VIDEOXMLMAX 8

#define STATUSBAR_NONE 0
#define STATUSBAR_COMX 1
#define STATUSBAR_DIAG 2
#define STATUSBAR_CIDELSA 3
#define STATUSBAR_VIP2 4

#define MATRIX_CTRL_KEY 0
#define MATRIX_SHIFT_KEY 1
#define MATRIX_CAPS_KEY 2
#define MATRIX_ESC_KEY 3
#define LAST_MATRIX_EF_KEY 4

#define MATRIX_RETURN_KEY 0
#define MATRIX_END_KEY 1
#define MATRIX_HOME_KEY 2
#define MATRIX_DOWN_KEY 3
#define MATRIX_LEFT_KEY 4
#define MATRIX_RIGHT_KEY 5
#define MATRIX_UP_KEY 6
#define LAST_MATRIX_TEXT_KEY 7

#define TAPE_FORMAT_AUTO 0
#define TAPE_FORMAT_PM 1
#define TAPE_FORMAT_56 2
#define TAPE_FORMAT_CV 3

enum
{
    COL_V1870_MAIN =56,
    COL_MC6845_FORE =64,
    COL_MC6845_BACK,
    COL_VT_FORE,
    COL_VT_BACK,
    COL_VT_HIGH,
    COL_PIXIE_FORE,
    COL_PIXIE_BACK,
    COL_I8275_FORE,
    COL_I8275_BACK,
    COL_I8275_HIGH,
    COL_MC6847_TEXT_BLACK,
    COL_MC6847_TEXT_GREEN,
    COL_MC6847_TEXT_ORANGE,
    COL_MC6847_GRAPH_GREEN,
    COL_MC6847_GRAPH_YELLOW,
    COL_MC6847_GRAPH_BLUE,
    COL_MC6847_GRAPH_RED,
    COL_MC6847_GRAPH_BUFF,
    COL_MC6847_GRAPH_CYAN,
    COL_MC6847_GRAPH_MAGENTA,
    COL_MC6847_GRAPH_ORANGE,
    COL_TMS_TRANSPARANT,
    COL_TMS_BLACK,
    COL_TMS_MEDIUM_GREEN,
    COL_TMS_LIGHT_GREEN,
    COL_TMS_DARK_BLUE,
    COL_TMS_LIGHT_BLUE,
    COL_TMS_DARK_RED,
    COL_TMS_AQUA_BLUE,
    COL_TMS_MEDIUM_RED,
    COL_TMS_LIGHT_RED,
    COL_TMS_DARK_YELLOW,
    COL_TMS_LIGHT_YELLOW,
    COL_TMS_DARK_GREEN,
    COL_TMS_PURPLE,
    COL_TMS_GRAY,
    COL_TMS_WHITE,
    COL_SN76430N_WHITE,
    COL_SN76430N_YELLOW,
    COL_SN76430N_GREEN,
    COL_SN76430N_RED,
    COL_SN76430N_BLACK,
    COL_MAX
};

#endif // COMPUTERCONFIG_H
